{% set version = "0.5.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-textrecipes
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/textrecipes_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/textrecipes/textrecipes_{{ version }}.tar.gz
  sha256: c53e136267bfe450eea342085f4585209b2aab4df0bb69d1878332b4d5ca4b7e

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-dials
    - r-dplyr
    - r-generics
    - r-magrittr
    - r-matrix
    - r-modeldata
    - r-purrr
    - r-rcpp
    - r-recipes >=0.1.4
    - r-rlang
    - r-snowballc
    - r-stopwords
    - r-stringr
    - r-tibble
    - r-tidyr
    - r-tokenizers
    - r-vctrs
  run:
    - r-base
    - r-base
    - r-dials
    - r-dplyr
    - r-generics
    - r-magrittr
    - r-matrix
    - r-modeldata
    - r-purrr
    - r-rcpp
    - r-recipes >=0.1.4
    - r-rlang
    - r-snowballc
    - r-stopwords
    - r-stringr
    - r-tibble
    - r-tidyr
    - r-tokenizers
    - r-vctrs

test:
  commands:
    - $R -e "library('textrecipes')"           # [not win]
    - "\"%R%\" -e \"library('textrecipes')\""  # [win]

about:
  home: https://github.com/tidymodels/textrecipes
  license: MIT
  summary: Converting text to numerical features requires specifically created procedures, which are implemented as steps according to the 'recipes' package. These steps allows for tokenization, filtering, counting (tf and tfidf) and feature hashing.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - philip-khor

# Package: textrecipes
# Title: Extra 'Recipes' for Text Processing
# Version: 0.0.2
# Authors@R: person(given = "Emil", family = "Hvitfeldt", role = c("aut", "cre"), email = "emilhhvitfeldt@gmail.com", comment = c(ORCID = "0000-0002-0679-1945"))
# Description: Converting text to numerical features requires specifically created procedures, which are implemented as steps according to the 'recipes' package. These steps allows for tokenization, filtering, counting (tf and tfidf) and feature hashing.
# License: MIT + file LICENSE
# URL: https://github.com/tidymodels/textrecipes
# BugReports: https://github.com/tidymodels/textrecipes/issues
# Depends: R (>= 2.10), recipes (>= 0.1.4)
# Imports: generics, rlang, tokenizers, dplyr, tibble, purrr, SnowballC, stopwords, magrittr, stringr, text2vec, textfeatures (>= 0.3.3), lifecycle
# Suggests: covr, testthat (>= 2.1.0), knitr, rmarkdown
# VignetteBuilder: knitr
# RdMacros: lifecycle
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 6.1.1
# SystemRequirements: GNU make, C++11
# NeedsCompilation: no
# Packaged: 2019-09-06 21:42:42 UTC; emilhvitfeldthansen
# Author: Emil Hvitfeldt [aut, cre] (<https://orcid.org/0000-0002-0679-1945>)
# Maintainer: Emil Hvitfeldt <emilhhvitfeldt@gmail.com>
# Repository: CRAN
# Date/Publication: 2019-09-07 11:20:02 UTC
