travis:
  secure:
    BINSTAR_TOKEN: ElwFSvUSPyfNprLaD5h2Z2FVCMCYxR1BM41ngjbwJWLA+EyYt//r7OiovzLXYtZqARDVLVzVVPW0HhF5LE3flIBcxVV0WLU4//KkdzDvTcuzNKc2RCUNNqGn5eQ8nxPaCOv2i1PNwO/kX+i7EYox97L1v+xNjFJX9aDGm4LnofJ8hte8dhxRHpC7Tbi2qINf8ascI7YUU4qPyhIVTDL+s8pAr9SJSdrTxr4NVmc4KaKU5r6iPWV+AN4sFGbyQvr2rUJKlPV5hUZCvR5H6ejP5nenCfKFOAkofqMc8qw1wcmBCjwdsic/iysB+x4aaliCvcabzxw1i9aiPbdfQ7fHIkw7I92eY0Rf+WuoxBJHMbGtFOIUzWtWN+RXIurPEKL+XoOiPaIwK6Zm+ZW+pYSt6Tajm7gM7TIpetHxK6fccXghqopOX8z8E+gNwREblHpPQdZHkvkRLJH/7ewcQ1NHgSvAgbYP3e+8UF6d1X2G1+kvMaPR4P+3KKjL6AQiqXXYIrRknV2p39GXyWGD8OcenhgOql2dZxQBtXf0nr8PVXPsG8qvaqxT8jsyQZjxfw8VmF9VXzlKqG44+Y2geWrCTplupiQpkRe9NlfJSXciTu1hywFadCfYiqPA4TayC6DnyQm/0vrJ2GEjV8o9Nv1nRodJuuO371rmpFZtgKkZDk0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
